### ISSUE TITLE
API Key in library instantiation not being used.

### ISSUE THREAD

**Issue by adomasven** [fcheslack/libZoteroJS#6]
The library key in `Zotero.Library` constructor is not being used. The one in `Zotero.config.apiKey` is used instead.

Not really sure what's the correct way to resolve this (i.e. fall back to the config value, but otherwise use the one specified on the library, remove the library one or remove the config one), but it would make sense to change it up to reduce confusion.

**Comment by fcheslack** [comment]
Yeah, this is complicated by a few things.
Using a separate auth mechanism on zotero.org, and using a common Zotero.Net instance that manages all requests (but in situations where you might want different permissions for different requests, which z.org doesn't have to deal with).

We should also probably pass the key in the auth header instead of the query string now that that's supported.

**Comment by fcheslack** [comment]
https://github.com/fcheslack/libZoteroJS/commit/a249d0e632e868c94e20a6c1a547c0c831355ec0
